### ISSUE TITLE
KDevelop support

### ISSUE THREAD

**Issue by Petross404** [dobokirisame/CompilerExplorer#19]
Hi,

Can this plugin support KDevelop as well?

**Comment by dobokirisame** [comment]
Hi, @Petross404.
I didn't plan to add kdevelop support. But i think it is not a big deal to rework project for that need. Actually i've abandoned this project for two years, and current version of Godbolt's complier explorer is far newer than this plugin supports.

**Comment by Petross404** [comment]
Thank you for your answer :)
